### ISSUE TITLE
nvm install latest installs latest unstable instead of stable

### ISSUE THREAD

**Issue by jordanbtucker** [coreybutler/nodedistro#10]
`nvm install latest` is installing 4.1.2 even though it's listed as unstable.

**Comment by coreybutler** [comment]
This has nothing to do with nodedistro. I assume this has to do with how [nvm-windows](https://github.com/coreybutler/nvm-windows) is processing the list (as opposed to nvm for *nix). Feel free to re-post this on the nvm-windows issues.
