### ISSUE TITLE
Consider adjusting your iron.io script for parsing node versions

### ISSUE THREAD

**Issue by andischerer** [coreybutler/nodedistro#12]
Hi,

first of all, thanks for your work :+1: !

Since the merge of nodejs and iojs the repository has moved from
https://github.com/joyent/node to https://github.com/nodejs/node.
Alternatively you could parse this file for version information: http://nodejs.org/dist/index.json

**Comment by coreybutler** [comment]
The script actually has changed.... looks like it might be a caching issue with iron.io.

**Comment by andischerer** [comment]
OK, i saw the link to the old joyent repo in the README section __How it works__

**Comment by coreybutler** [comment]
Done!
