### ISSUE TITLE
Latest versions update

### ISSUE THREAD

**Issue by djsylvester** [coreybutler/nodedistro#22]
The list was updated for node v5.8.0 and v4.4.0 to use the latest npm version. Node 5.9.0 stable is now out but npm is still loading v3.7.3.

Would you please update the json file for node v5.9.0 to use npm v3.8.1.

**Comment by coreybutler** [comment]
This list identifies the version of npm that _ships_ with each version of node. Node 5.9.0 ships with npm v3.7.3, even though the latest version of npm is 3.8.1.
