### ISSUE TITLE
Node 4.0.0

### ISSUE THREAD

**Issue by ArtskydJ** [coreybutler/nodedistro#7]
```bash
C:\Windows\system32>nvm install 4.0.0 32
Version 4.0.0 is not available. If you are attempting to download a "just released" version,
it may not be recognized by the nvm service yet (updated hourly). If you feel this is in error and
you know the version exists, please visit http://github.com/coreybutler/nodedistro and submit a PR.
```

[Node v4.0.0 was released](https://github.com/nodejs/node/releases) about 2 hours ago.

**Comment by ArtskydJ** [comment]
Perhaps this is an issue with whatever job that builds this json file. Maybe it is watching joyent/node/releases, not nodejs/node/releases?

**Comment by coreybutler** [comment]
You're right, it was pointing to the old repo. I've fixed it and the script completes with a success message... but it's still not updating. I'll update by hand for now and look into this when I have more time.

**Comment by Efreak** [comment]
It grabs 4.0.0 ok, but it installs npm 2.11.3 instead of 2.14.2 (also, the previous version was 2.13.3; I'm not sure how old 2.11.3 is)

**Comment by peter-vdc** [comment]
FYI: for some reason it says for node 4.0.0 that only the 32-bit version is available

**Comment by prijindal** [comment]
Yes it says that Node.js v4.0.0 is only available in 32-bit.

**Comment by coreybutler** [comment]
The 32-bit issue has nothing to do with nodedistro. The bitness is part of nvm-windows, which should be corrected in the most recent release.
