### ISSUE TITLE
4.1.1 and 4.1.2 are listed as unstable

### ISSUE THREAD

**Issue by jordanbtucker** [coreybutler/nodedistro#9]
What is the rationale behind 4.1.1 and 4.1.2 being listed as unstable? They're both listed as stable on their blog.

https://nodejs.org/en/blog/release/v4.1.1/

https://nodejs.org/en/blog/release/v4.1.2/

**Comment by jordanbtucker** [comment]
4.2.1 is also listed as unstable.

**Comment by coreybutler** [comment]
With the introduction of LTS, there isn't really a stable/unstable anymore. I have updated the script to identify any LTS release as "stable" and anything else as unstable until a better approach can be implemented.
